name: MainBuildPopinWebsViewDemo
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup gradle
      run: chmod +x ./gradlew
    - name: Running linter
      run: ./gradlew lint
    - name: Building debug
      run: ./gradlew app:assembleDebug
    - uses: MeilCli/slack-upload-file@v3
      with:
        slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
        channel_id: C04M527K2FQ
        file_path: app/build/outputs/apk/debug/app-debug.apk
        initial_comment: "Webview Demo: ${{ github.event.head_commit.message }}"
    - name: Report Status
      if: always()
      uses: ravsamhq/notify-slack-action@v2
      with:
        status: ${{ job.status }}
        notify_when: 'failure'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
